16_3: 16_3.o Sales_data.o
	g++ -o 16_3 16_3.o Sales_data.o -std=c++11

16_3.o: 16_3.cpp 16_3.h Sales_data.h
	g++ -c 16_3.cpp -std=c++11

Sales_data.o: Sales_data.cpp
	g++ -c Sales_data.cpp -std=c++11
